#
OPT += --release=fast
#OPT += --release=small
# Fail compilation
#OPT += --release=safe

include ../makefile.common.header.mk


#AFTER_BUILD_CMD = strip $(TARGET_EXE)


include ../makefile.common.mk
