name: Linux OS(Ubuntu) zig-0.15.1 compilation-

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: mlugg/setup-zig@v2
      with:
        version: 0.15.1
    - name: make
      run: |
        sudo apt-get install --fix-missing libopengl-dev libgl1-mesa-dev libglfw3 libglfw3-dev
        make
