name: Windows OS zig-0.15.1 compilation-

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  win_release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: mlugg/setup-zig@v2
      with:
        version: 0.15.1
    - name: Show zig path
      shell: pwsh
      run: |
        Get-Command zig
        where zig
        echo $env:PATH
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
    - name: make
      run: |
        where zig
