name: Windows OS zig-0.16.0 compilation-

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  win_dev:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: mlugg/setup-zig@v2
      with:
        version: master
    - name: make
      run: |
        pacman -S mingw-w64-x86_64-{gcc,glfw,SDL2,sdl3} make
        make
