name: Windows OS zig-0.15.1 compilation-

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  win_release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: mlugg/setup-zig@v2
      with:
        version: 0.15.1
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
    - name: make
      shell: msys2 {0}
      run: |
        export PATH="$PATH:$(dirname $(cygpath -u "$(where zig | head -n 1)"))"
        pacman -S --noconfirm mingw-w64-x86_64-{gcc,glfw,sdl3,pkg-config} make
        make
