name: Zig CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019


    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0

    - name: make
      run: make
